function LEDctrlGUI

global obj ardCOM

obj = drawGUIfig;

% Initialize serial communication with arduino
ardCOM = initializeArduino;

strobe_callback([],1); % make sure there is a string for strobe ctrl
end

% =========================================================================
%% callbacks

function blueON_callback(~,event)
global obj ardCOM
if get(obj.blueON,'value') == true
    set(obj.blueON,'string','Blue LED OFF','foregroundcolor',[0 0 .5])
    fprintf(ardCOM,['t' num2str(LEDparams.blueLEDch)]);
else
    set(obj.blueON,'string','Blue LED ON','foregroundcolor','b')
    fprintf(ardCOM,['t' num2str(LEDparams.blueLEDch)]);
end
end

function greenON_callback(~,event)
global obj ardCOM
if get(obj.greenON,'value') == true
    set(obj.greenON,'string','Green LED OFF','foregroundcolor',[0 .3 0])
    fprintf(ardCOM,['t' num2str(LEDparams.greenLEDch)]);
else
    set(obj.greenON,'string','Green LED ON','foregroundcolor',[0 .7 0])
    fprintf(ardCOM,['t' num2str(LEDparams.greenLEDch)]);
end
end

function ledsOff_callback(~,event)
global obj ardCOM
if get(obj.ledsOff,'value') == true
    fprintf(ardCOM,'x');
end
end

function strobe_callback(~,event)
global obj 
obj.strobeSeqLetters = get(obj.strobe,'string');

% transform B and G into channel number
obj.strobeSeq = [];
for ii = 1:length(obj.strobeSeqLetters)
    if strcmpi(obj.strobeSeqLetters(ii),'B')
        obj.strobeSeq = [obj.strobeSeq num2str(LEDparams.blueLEDch)];
    elseif strcmpi(obj.strobeSeqLetters(ii),'G')
        obj.strobeSeq = [obj.strobeSeq num2str(LEDparams.greenLEDch)];
    end
end    
    
end

function sendStrobe_callback(~,event)
global obj ardCOM
if get(obj.sendStrobe,'value') == true
    fprintf(ardCOM,'f');  
    fprintf(ardCOM,['s' obj.strobeSeq]);
end
end

function camCtrl_callback(~,event)
global obj ardCOM
if get(obj.camCtrl,'value') == true
    fprintf(ardCOM,'c');
    fprintf(ardCOM,'f');
end
end

function reset_callback(~,event)
global obj ardCOM
if get(obj.reset,'value') == true
    if ~isempty(instrfindall)
        fprintf(ardCOM,'x');
        terminateArduino(ardCOM);
%         clear ardCOM
    end
    close(obj.guifig);
    LEDctrlGUI
%     ardCOM = initializeArduino;
end
end

function quit_callback(~,event)
global obj ardCOM
if get(obj.quit,'value') == true
    try
    if ~isempty(instrfindall)
        terminateArduino(ardCOM);
    end
    end
    close(obj.guifig)
end
end

% =========================================================================
%% DRAW GUI OBJECT
function obj = drawGUIfig


% create GUI figure
ss = get(groot,'screensize');
ss = ss(3:4);
obj.guifig    =   figure    ('Name',            'LED control',     ...
                          'NumberTitle',        'off',                      ...
                          'Position',           round([ss(1)*.5 ss(2)*.5 ss(1)*.2 ss(2)*.3]));
obj.strobeSeqLetters = 'BBBG';

% -------------------------------------------------------------------------
%% general control buttons
% -------------------------------------------------------------------------                      
obj.blueON =    uicontrol   ('Parent',          obj.guifig,         ...
                        'Style',                'togglebutton',     ...
                        'String',               'Blue LED ON',      ...
                        'Units',                'normalized',       ...
                        'Position',             [.05 .75 .40 .20],  ...
                        'horizontalAlignment',  'center',           ...
                        'foregroundColor',      'b',                ...
                        'fontweight',           'bold',             ...
                        'fontsize',             13,                 ...
                        'Callback',             @blueON_callback);
obj.greenON =   uicontrol   ('Parent',          obj.guifig,         ...
                        'Style',                'togglebutton',     ...
                        'String',               'Green LED ON',     ...
                        'Units',                'normalized',       ...
                        'Position',             [.05 .50 .40 .20],  ...
                        'horizontalAlignment',  'center',           ...
                        'foregroundColor',      [0 .7 0],           ...
                        'fontweight',           'bold',             ...
                        'fontsize',             13,                 ...
                        'Callback',             @greenON_callback);
obj.ledsOff =   uicontrol   ('Parent',          obj.guifig,         ...
                        'Style',                'pushbutton',       ...
                        'String',               'Turn off LEDs',    ...
                        'Units',                'normalized',       ...
                        'Position',             [.05 .27 .40 .20],  ...
                        'horizontalAlignment',  'center',           ...
                        'foregroundColor',      [0 0 0],            ...
                        'fontweight',           'bold',             ...
                        'fontsize',             13,                 ...
                        'Callback',             @ledsOff_callback);
                    
obj.strobeTxt =   uicontrol   ('Parent',          obj.guifig,       ...
                        'Style',                'text',             ...
                        'String',               'Strobe sequence:', ...
                        'Units',                'normalized',       ...
                        'Position',             [.51 .75 .45 .20],  ...
                        'horizontalAlignment',  'center',           ...
                        'foregroundColor',      'k',                ...
                        'fontweight',           'bold',             ...
                        'fontsize',             13);
obj.strobe    =   uicontrol   ('Parent',          obj.guifig,       ...
                        'Style',                'edit',             ...
                        'String',               obj.strobeSeqLetters,...
                        'Units',                'normalized',       ...
                        'Position',             [.53 .68 .42 .15],  ...
                        'horizontalAlignment',  'center',           ...
                        'foregroundColor',      [.3 .3 .3],         ...
                        'fontsize',             13,                 ...
                        'Callback',             @strobe_callback);
obj.sendStrobe =   uicontrol   ('Parent',       obj.guifig,         ...
                        'Style',                'pushbutton',       ...
                        'String',               'send',             ...
                        'Units',                'normalized',       ...
                        'Position',             [.62 .50 .23 .13],  ...
                        'horizontalAlignment',  'center',           ...
                        'foregroundColor',      [0 0 0],            ...
                        'fontweight',           'bold',             ...
                        'fontsize',             13,                 ...
                        'Callback',             @sendStrobe_callback);
                    
obj.camCtrl =   uicontrol   ('Parent',            obj.guifig,       ...
                        'Style',                'pushbutton',       ...
                        'String',               'shut cam ctrl',    ...
                        'Units',                'normalized',       ...
                        'Position',             [.05 .05 .29 .20],  ...
                        'horizontalAlignment',  'center',           ...
                        'foregroundColor',      'k',                ...
                        'fontweight',           'bold',             ...
                        'fontsize',             13,                 ...
                        'Callback',             @camCtrl_callback);
obj.reset =   uicontrol   ('Parent',            obj.guifig,         ...
                        'Style',                'pushbutton',       ...
                        'String',               'reset Arduino',    ...
                        'Units',                'normalized',       ...
                        'Position',             [.36 .05 .29 .20],  ...
                        'horizontalAlignment',  'center',           ...
                        'foregroundColor',      [.5 0 0],           ...
                        'fontweight',           'bold',             ...
                        'fontsize',             13,                 ...
                        'Callback',             @reset_callback);
obj.quit =   uicontrol   ('Parent',              obj.guifig,        ...
                        'Style',                'pushbutton',       ...
                        'String',               'quit',             ...
                        'Units',                'normalized',       ...
                        'Position',             [.67 .05 .29 .20],  ...
                        'horizontalAlignment',  'center',           ...
                        'foregroundColor',      'r',                ...
                        'fontweight',           'bold',             ...
                        'fontsize',             13,                 ...
                        'Callback',             @quit_callback);
                    
end